### PR TITLE
Fix in mlkit face detection sample app for ears detection (#700)

### PR DESCRIPTION
**Pull request by MarianIacob**
Related issue:
https://github.com/firebase/quickstart-android/issues/700

### CODE REVIEW

**Comment by MarianIacob** [comment]
I signed it!

**Comment by MarianIacob** [comment]
Used a different mail in the commit, updated and should be fine now.

**Comment by samtstern** [comment]
Going to merge over Travis since tests were broken by @kroike in this commit:
https://github.com/firebase/quickstart-android/commit/48905dee442436a6fefaf67d03a92fca7e47d9ed#diff-bb2861375ce7d8f6313fafe6bbfb5834

**Comment by samtstern** [comment]
Thanks @MarianIacob !

**Pull request merged**
