### PR TITLE
Update Android Gradle Plugin to 3.3.0-alpha08. This causes the google_app_id not to be generated.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by rosariopfernandes** [comment]
The Android Gradle Plugin version 3.1.4 works fine on my side. Which version of Android Studio are you using? @vanniktech

**Comment by samtstern** [comment]
@rosariopfernandes I think this is a specific issue with `3.3.0-alpha08` combined with `google-services` version `4.1.0`.  I am gonna check it out on a clean project.

**Comment by vanniktech** [comment]
Haven't tried out alpha09 which just got released today. But yes AGP 3.3.0-alpha08 and Google Play Services Plugin 4.1.0 do not play along nicely. Namely, it does not generate the xml resource file containing the extracted information from the `play-services.json` file.

The temporary workaround is to use 4.0.1 or 4.0.2 which does work with the 3.3.0-alpha versions.

**Comment by samtstern** [comment]
@vanniktech was able to reproduce!  Doesn't look like the plugin even runs, since I can apply the `4.1.0` plugin to a project with no `json` file and have the build succeed.

Thanks for this!  I will flag it to the right people.

**Comment by samtstern** [comment]
Plugin owner says: "Yes, I had someone report it earlier this week, I've been investigating"

@vanniktech if you're still in contact with Firebase support you can tell them this is a duplicate of bug 114445730

**Comment by the-dagger** [comment]
Unrelated : @vanniktech Thanks a ton for your [samples on lint](https://github.com/vanniktech/lint-rules), they helped a lot while I was working on #658! 🎉

**Comment by vanniktech** [comment]
Sent it back to Firebase support. Thanks for helping out.

**Comment by vanniktech** [comment]
@the-dagger I've reviewed your PR here about lint.

**Comment by the-dagger** [comment]
Thanks @vanniktech.
Added some followup comments, have a look whenever convenient!

**Comment by samtstern** [comment]
Going to close this as we have an internal repro, so leaving this PR open doesn't do that much.  Will update when we know more!

**Comment by b95505017** [comment]
Any updates? 3.3 is going to beta now, and still can't work with 4.1.0.

**Comment by LouisCAD** [comment]
@samtstern Is there an issue we can follow?

**Comment by eygraber** [comment]
Google services plugin 4.2.0 fixes the problem for me

**Comment by samtstern** [comment]
@eygraber nice!  Thanks for following up.

@LouisCAD no there is not, but if you get the same issues with `4.2.0` please file a new issue!

**Pull request closed without merging**
