### PR TITLE
Add FCM to the Functions sample to exercise IID integration.

### PR DESCRIPTION
**Pull request by bklimt**

### CODE REVIEW

**Comment by samtstern** [comment]
LGTM once Travis goes green.

**Comment by bklimt** [comment]
Thanks. Travis is failing because I haven't added FCM to the gradle file yet. I'll do that before I submit.

**Comment by samtstern** [comment]
@bklimt any update on this/

**Comment by bklimt** [comment]
Thanks for the reminder. I pushed the new build.gradle. If Travis turns green, I'll merge.

**Comment by samtstern** [comment]
@bklimt thanks!  Make sure to use the "Squash and Merge" option

**Comment by bklimt** [comment]
Yes, of course. I'm surprised the repo even allows merge commits.

**Pull request merged**
