### PR TITLE
[OPTIMIZE]Slight optimize the context and activity issue of the CustomImageClassifier feature

### PR DESCRIPTION
**Pull request by XinyueZ**

### CODE REVIEW

**Comment by samtstern** [comment]
LGTM but maybe we should let @the-dagger merge his PR first to avoid a conflict?

**Comment by XinyueZ** [comment]
have no objections 🤝 
https://github.com/firebase/quickstart-android/pull/736#issuecomment-437076230

**Comment by samtstern** [comment]
#721 has been merged now, so after conflicts are resolved here we can merge this as well

**Comment by XinyueZ** [comment]
@samtstern done, pls check

**Comment by samtstern** [comment]
@XinyueZ LGTM!  Will merge when green.

**Pull request merged**
