### PR TITLE
suggested change

### PR DESCRIPTION
**Pull request by Chitvan14**

### CODE REVIEW

**Comment by samtstern** [comment]
@Chitvan14 thanks for the PR but we don't say "Google Firebase", just Firebase!

**Comment by rosariopfernandes** [comment]
@samtstern I feel like this is just a PR to +1 their PR count on Hacktoberfest. I would suggest labelling it as "invalid" to discourage other participants from doing the same. Context: https://hacktoberfest.digitalocean.com/hacktoberfest-update
I fear we'll be getting many of these throughout the month.

---

@Chitvan14 please take some time to read the [Hacktoberfest Quality Guidelines](https://hacktoberfest.digitalocean.com/details#quality).
A better way to contribute to Open Source is too look at the Repo's Issue Tracker and see what they actually need, instead of trying to make documentation changes which don't really add much to the project.
Some resources that you might find useful:
- [Hacktoberfest - Ideas for Contributing as a Beginner ](https://dev.to/mcastellin/hacktoberfest-ideas-for-contributing-as-a-beginner-4k3b)
- [Hacktoberfest Etiquette for Contributors ](https://dev.to/devteam/hacktoberfest-etiquette-for-contributors-ec6)

**Comment by samtstern** [comment]
@rosariopfernandes I sort of suspected that but didn't want to accuse anyone!  Agree, if this is related to Hacktoberfest it's not within the guidelines.

**Comment by Chitvan14** [comment]
Hey ,
My intention was not to take part in hacktoberfest but I usually listened
Google firebase before...so when I come up with your repo...I found that
missing...and seemed to add that...but after @samtstern reply to me I came
to know that we can also recall Google firebase as only firebase...
@samtstern Thank you for letting me learn
@rosariopfernandes I am sorry if you feel it was an action of netiquette

**Comment by samtstern** [comment]
@Chitvan14 no worries!

**Comment by rosariopfernandes** [comment]
@Chitvan14 no problems. I'm glad you understand our concern. I'm sorry for the false accusation.

**Pull request closed without merging**
