### PR TITLE
Update EmailPasswordFragment.java

### PR DESCRIPTION
**Pull request by BranMik**
Simple bug fix in EmailPasswordFragment.java class of auth app, where signOutButton was bound to createAccount() action and emailCreateAccountButton was not bound at all.

### CODE REVIEW

**Comment by BranMik** [comment]
@googlebot I signed it!

**Review by rosariopfernandes — APPROVED** [review]
Thanks @BranMik !

**Comment by BranMik** [comment]
No probs, cheers.

**Comment by samtstern** [comment]
@BranMik thank you!

**Pull request merged**
