### PR TITLE
Refactor Storage sample to download in background

### PR DESCRIPTION
**Pull request by samtstern**
Move download to a background service which notifies the user via a Notification when the download is in progress/completed.

This prevents bad UX if the user leaves the app before download is finished.

### CODE REVIEW

**Comment by samtstern** [comment]
@kroikie please review.  Sorry, this is a big one.

**Comment by kroikie** [comment]
Np I'll have a look.

**Comment by samtstern** [comment]
Note to self: this will break includecode, do not submit without pending CL to fix that

**Comment by kroikie** [comment]
LGTM, assuming the TODOs are addressed in a future PR.

**Comment by samtstern** [comment]
Good call on the TODOs, I actually did address them but forgot to remove the notes.  Will update.

**Pull request merged**
