### PR TITLE
Bump vertex version to beta01

### PR DESCRIPTION
**Pull request by rlazo**

### CODE REVIEW

**Comment by rlazo** [comment]
btw, ci breakage is expected since functioncalls have changed. Will fix in follow up PR

**Comment by thatfiredev** [comment]
@rlazo  I'm happy to help fix in this PR. I'll make changes directly to your branch if that's ok

**Comment by rlazo** [comment]
sure, go ahead!

**Comment by thatfiredev** [comment]
@rlazo ptal at the latest commit

**Comment by rlazo** [comment]
> @rlazo ptal at the latest commit

LGTM. We can work later on make the example extensible to support multiple function calls in parallel

**Review by thatfiredev — APPROVED** [review]

**Pull request merged**
