### PR TITLE
Update MLKit with latest API changes.

### PR DESCRIPTION
**Pull request by gkaldev**
Also adds preferences configuration (to be refactored with Jetpack prefs soon)

### CODE REVIEW

**Comment by samtstern** [comment]
Looks like you need to run `./gradlew ktlint` from the root of `quickstart-android`

```
> Task :ktlint
/home/travis/build/firebase/quickstart-android/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/automl/AutoMLImageLabelerProcessor.kt:27:24: Wildcard import (cannot be auto-corrected)
"checkstyle" report written to /home/travis/build/firebase/quickstart-android/build/reports/ktlint/ktlint-checkstyle-report.xml
> Task :ktlint FAILED
```

**Comment by gkaldev** [comment]
Nvm, just had to wait longer.

**Comment by samtstern** [comment]
```
> Task :mlkit-translate:app:compileDebugKotlin FAILED
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (30, 57): Unresolved reference: FirebaseTranslateModelManager
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (37, 31): Unresolved reference: FirebaseTranslateModelManager
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (38, 9): Unresolved reference: FirebaseTranslateModelManager
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (80, 37): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (82, 45): Unresolved reference: it
e: /home/travis/build/firebase/quickstart-android/mlkit-translate/app/src/main/java/com/google/firebase/samples/apps/mlkit/translate/kotlin/TranslateViewModel.kt: (82, 69): Unresolved reference: it
```

**Comment by gkaldev** [comment]
ktlint always succeeds when I do it locally, for some reason. Anyway, fyi, doing this fix and check-on-server-side process until I fix my local setup.

**Comment by samtstern** [comment]
@gkaldev so `ktlint` locally runs with `--fix` which means you need to commit the changes it makes after it makes them.

**Comment by gkaldev** [comment]
Used to work like that for me too, but now I don't see any local pending changes, staged or not, when there are clearly lint-fixable errors in source.

**Comment by samtstern** [comment]
@gkaldev by the way feel free to open future PRs from a branch on this repo if you find dealing with forks annoying (I do).  That will also run the second build which exposes proguard errors (which don't seem to happen much anymore).

**Pull request merged**
