### PR TITLE
Fix App Indexing build

### PR DESCRIPTION
**Pull request by samtstern**
Change-Id: I107c73eb741a686847eedb63bf854b92bae3b4e9

### CODE REVIEW

**Comment by friederbluemle** [comment]
@samtstern What was the Lint error you were seeing? The build passes with only warning for me locally (no need to ignore errors).

**Comment by friederbluemle** [comment]
All projects now build successfully without ignoring errors: #66

**Comment by samtstern** [comment]
@friederbluemle the strange thing is the lint error was only occurring on Travis CI, and since app-indexing was the only sub-project not already ignoring them I just added that to get the build back to green.

Thanks a ton for #66, I will take a look now.

**Comment by friederbluemle** [comment]
@samtstern Yeah, I just noticed the Travis CI error after submitting #66. I think the error is because of an outdated `platform-tools` component on Travis. I added commit cdb0224d52fa25bd9f23ca08f403dbf371194f27 which should fix it.

**Pull request merged**
